version: "3"

services:
  db: 
    image: mysql:5.7.20
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "(password123)" #probably should change this
      MYSQL_DATABASE: "containerdb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user1234"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ${PWD}/www:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - "8080:80"
    depends_on:
      - db
